# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/GRPCServer2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/GRPCServer2.proto',
  package='GPRCServer2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18protos/GRPCServer2.proto\x12\x0bGPRCServer2\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"&\n\x0c\x66irstRequest\x12\x16\n\x04name\x18\x01 \x01(\tB\x08\xfa\x42\x05r\x03\x98\x01\x03\"\x1c\n\rfirstResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"%\n\x0blastRequest\x12\x16\n\x04name\x18\x01 \x01(\tB\x08\xfa\x42\x05r\x03\x98\x01\x03\"\x1b\n\x0clastResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xd4\x01\n\nGPRCServer\x12`\n\x0b\x63onnectGRPC\x12\x19.GPRCServer2.firstRequest\x1a\x1a.GPRCServer2.firstResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12\x61pi/connect/{name}\x12\x64\n\x0e\x64isconnectGRPC\x12\x18.GPRCServer2.lastRequest\x1a\x19.GPRCServer2.lastResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15\x61pi/disconnect/{name}b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,validate_dot_validate__pb2.DESCRIPTOR,])




_FIRSTREQUEST = _descriptor.Descriptor(
  name='firstRequest',
  full_name='GPRCServer2.firstRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GPRCServer2.firstRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\005r\003\230\001\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=134,
)


_FIRSTRESPONSE = _descriptor.Descriptor(
  name='firstResponse',
  full_name='GPRCServer2.firstResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='GPRCServer2.firstResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=164,
)


_LASTREQUEST = _descriptor.Descriptor(
  name='lastRequest',
  full_name='GPRCServer2.lastRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GPRCServer2.lastRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\005r\003\230\001\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=203,
)


_LASTRESPONSE = _descriptor.Descriptor(
  name='lastResponse',
  full_name='GPRCServer2.lastResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='GPRCServer2.lastResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=232,
)

DESCRIPTOR.message_types_by_name['firstRequest'] = _FIRSTREQUEST
DESCRIPTOR.message_types_by_name['firstResponse'] = _FIRSTRESPONSE
DESCRIPTOR.message_types_by_name['lastRequest'] = _LASTREQUEST
DESCRIPTOR.message_types_by_name['lastResponse'] = _LASTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

firstRequest = _reflection.GeneratedProtocolMessageType('firstRequest', (_message.Message,), {
  'DESCRIPTOR' : _FIRSTREQUEST,
  '__module__' : 'protos.GRPCServer2_pb2'
  # @@protoc_insertion_point(class_scope:GPRCServer2.firstRequest)
  })
_sym_db.RegisterMessage(firstRequest)

firstResponse = _reflection.GeneratedProtocolMessageType('firstResponse', (_message.Message,), {
  'DESCRIPTOR' : _FIRSTRESPONSE,
  '__module__' : 'protos.GRPCServer2_pb2'
  # @@protoc_insertion_point(class_scope:GPRCServer2.firstResponse)
  })
_sym_db.RegisterMessage(firstResponse)

lastRequest = _reflection.GeneratedProtocolMessageType('lastRequest', (_message.Message,), {
  'DESCRIPTOR' : _LASTREQUEST,
  '__module__' : 'protos.GRPCServer2_pb2'
  # @@protoc_insertion_point(class_scope:GPRCServer2.lastRequest)
  })
_sym_db.RegisterMessage(lastRequest)

lastResponse = _reflection.GeneratedProtocolMessageType('lastResponse', (_message.Message,), {
  'DESCRIPTOR' : _LASTRESPONSE,
  '__module__' : 'protos.GRPCServer2_pb2'
  # @@protoc_insertion_point(class_scope:GPRCServer2.lastResponse)
  })
_sym_db.RegisterMessage(lastResponse)


_FIRSTREQUEST.fields_by_name['name']._options = None
_LASTREQUEST.fields_by_name['name']._options = None

_GPRCSERVER = _descriptor.ServiceDescriptor(
  name='GPRCServer',
  full_name='GPRCServer2.GPRCServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=235,
  serialized_end=447,
  methods=[
  _descriptor.MethodDescriptor(
    name='connectGRPC',
    full_name='GPRCServer2.GPRCServer.connectGRPC',
    index=0,
    containing_service=None,
    input_type=_FIRSTREQUEST,
    output_type=_FIRSTRESPONSE,
    serialized_options=b'\202\323\344\223\002\024\022\022api/connect/{name}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='disconnectGRPC',
    full_name='GPRCServer2.GPRCServer.disconnectGRPC',
    index=1,
    containing_service=None,
    input_type=_LASTREQUEST,
    output_type=_LASTRESPONSE,
    serialized_options=b'\202\323\344\223\002\027\022\025api/disconnect/{name}',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GPRCSERVER)

DESCRIPTOR.services_by_name['GPRCServer'] = _GPRCSERVER

# @@protoc_insertion_point(module_scope)
